image: ubuntu:16.04

stages:
  - build
  - test

#Files that are needed for tests from build environment
#cache:
#  paths:
#    - examples/pipeflow/pipeflow
#    - examples/stretchCell/stretchCell

before_script:
  - apt-get update > /dev/null
  - apt-get -y install git bc make cmake g++-5 g++ libopenmpi-dev libhdf5-dev patch python-h5py wget > /dev/null
  - cd ${CI_PROJECT_DIR}
  - ./setup.sh > /dev/null

build_cases:
  stage: build
  script:
    - cd ${CI_PROJECT_DIR}/examples
    - make -j4 all > /dev/null
  artifacts:
    expire_in: 2 hrs
    paths:
      - examples/pipeflow/pipeflow
      - examples/stretchCell/stretchCell

test_pipeflow:
  stage: test
  script:
    - ${CI_PROJECT_DIR}/scripts/ci/pipeflow_sanity.sh
  dependencies:
    - build_cases

test_stretchCell:
  stage: test
  script:
    - ${CI_PROJECT_DIR}/scripts/ci/stretchCell_sanity.sh
  dependencies:
    - build_cases
